#! /usr/bin/env node

var mongoose = require('mongoose');
var Vote = require('./models/vote');
var async = require('async');

function seed() {
  mongoose.connect('mongodb://bahama-llama:llamallama@ds029426.mlab.com:29426/heroku_vjlvzhh6');

  var llamas = [
    'sherriff_llama',
    'deep_llama',
    'suspicious_llama',
    'photogenic_llama',
    'surfer_dude_llama',
    'unhappy_llama',
    'happy_llama',
    'canadian_llama'
  ];

  for (llama of llamas) {
    seedVote(llama, llama, llama + "@llama.com");
  }

  Vote.remove({}, (err) => {
    if (err) console.error(err);

    var voters = [
      {
        email: 'warrenzevon@llama.com',
        name: 'Warren Zevon'
      },
      {
        email: 'keithrichards@llama.com',
        name: 'Keith Richards'
      },
      {
        email: 'micktaylor@llama.com',
        name: 'Mick Taylor'
      },
      {
        email: 'garyclarkjr@llama.com',
        name: 'Gary Clark, Jr.'
      },
      {
        email: 'literallyallfourbeatles@llama.com',
        name: 'Literally All Four Beatles'
      },
      {
        email: 'theworstkindofperson@llama.com',
        name: 'The Worst Kind of Person'
      },
      {
        email: 'llamaking@llama.com',
        name: 'LLama King, IV'
      },
      {
        email: 'darthvader@llama.com',
        name: 'Darth Vader'
      },
      {
        email: 'ravishankar@llama.com',
        name: 'Ravi Shankar'
      },
      {
        email: 'donovan@llama.com',
        name: 'Donovan'
      }
    ];

    while (voters.length > 0) {
      var voter = voters.pop();
      seedVote(randomLlama(llamas), voter.name, voter.email);
    }
  });
};

function randomLlama(llamas) {

  var index = Math.floor((Math.random() * llamas.length));
  return llamas[index];
}

function seedVote(llama, name, email) {
  var vote = new Vote({
    name: name,
    email: email,
    vote: llama
  });
  vote.save((err, vote) => {
    if (err) console.error(err);
    console.log(vote);
  });
}

seed();
